title: Yuyou Yao
description: Yuyou Yao is a lecture in School of Public Safety and Emergency Management, Anhui University of Science & Technology.
show_downloads: false
theme: jekyll-theme-hacker
email: yaoyy@aust.edu.cn
url: https://Yaoyyaust/Yaoyyaust.github.io
